name: reactive_notifier
version: 2.15.0
issueTracker: https://github.com/jhonacode/reactive_notifier/issues
materialIconCodePoint: '0xe869'  # memory icon for state management
requiresConnection: true  # Requires VM Service connection to show real-time data