name: reactive_notifier
version: 2.13.0
issueTracker: https://github.com/jhonacode/reactive_notifier/issues
materialIconCodePoint: '0xe869'  # memory icon for state management
requiresConnection: false  # Can work without running app - shows all instances