name: reactive_notifier_devtools_extension
description: DevTools extension for ReactiveNotifier state management library

publish_to: none

version: 1.0.0

environment:
  sdk: ^3.5.4
  flutter: ">=3.16.0"

dependencies:
  devtools_extensions: ^0.0.4
  flutter:
    sdk: flutter
  collection: ^1.18.0
  web: ^1.0.0
  reactive_notifier:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true